### ISSUE TITLE
Error message off screen, seemingly no feedback

### ISSUE THREAD

**Issue by bennuttall** [astro-pi/beta-testing#20]
On my laptop (1600x900 resolution), the error message is shown off screen, and there's no indication that an error has occurred:

![screenshot from 2016-07-20 14-45-43](https://cloud.githubusercontent.com/assets/1609725/16988628/ee880772-4e88-11e6-9803-c6c3df1cfd0a.png)

Scrolled down:

![screenshot from 2016-07-20 14-45-50](https://cloud.githubusercontent.com/assets/1609725/16988627/ee6bb6da-4e88-11e6-9164-09994f36e6eb.png)

If the error could pop up or the editor went red, or the error line was highlighted, anything that would indicate there's an issue would be really helpful.

**Comment by eah13** [comment]
Thanks for this!  Working on making the errors more visible via an indicator in the file tab that has the error.  Also, in the example you gave a bug was preventing that import statement from being highlighted in red like a normal error, and that'll be fixed next deploy.  Between the two there should be a lot more going on above the fold.  We also likely should make the demo iframe a little smaller so more of it is visible on more screens.

**Comment by eah13** [comment]
@bennuttall thanks again for finding this.  This is now fixed!  There is a Red icon in the tab of the error and the line is highlighted.  

![screenshot 2016-07-25 at 1 21 22 pm](https://cloud.githubusercontent.com/assets/1702745/17110405/cb9a2b9c-526a-11e6-8167-a5a54a72f682.png)

In Epiphany and other browsers where we've disabled Ace, the line number of the error will turn red.

Closing as fixed, but feel free to drop further feedback here.

**Comment by davidhoness** [comment]
I've discovered that this still happens if the error is not caused by bad syntax, for example an incorrect parameter type:

``` python
from sense_hat import SenseHat
sense = SenseHat()
sense.set_rotation(75)
```

**Comment by eah13** [comment]
Nice find.  Looking into this.

**Comment by eah13** [comment]
@davidhoness Fixed!  Thanks again for finding this.
![screenshot 2016-08-02 at 9 57 13 am](https://cloud.githubusercontent.com/assets/1702745/17331107/89da0708-5897-11e6-8143-fd46683dfaca.png)
